export interface LocalRecipe {
  id: string
  name: string
  description: string
  difficulty: 'Fácil' | 'Media' | 'Difícil'
  prep_time: number
  instructions: string
  servings: number
  recipe_ingredients: { ingredient_name: string }[]
}

export const INITIAL_RECIPES: LocalRecipe[] = [
  {
    id: 'rec-tortilla',
    name: 'Tortilla',
    description: 'Tortilla casera y jugosa. La mejor forma de aprovechar huevos y cebolla antes de que se echen a perder.',
    difficulty: 'Fácil',
    prep_time: 15,
    instructions: '1. Pica la cebolla finamente y póchala en una sartén con un poco de aceite a fuego medio durante 8 minutos hasta que esté tierna.\n2. Bate los huevos en un bol con una pizca de sal.\n3. Incorpora la cebolla pochada al huevo batido.\n4. Cuaja la tortilla en la sartén 2-3 minutos por cada lado hasta que quede dorada por fuera y jugosa por dentro.',
    servings: 2,
    recipe_ingredients: [
      { ingredient_name: 'huevo' },
      { ingredient_name: 'cebolla' },
    ],
  },
  {
    id: 'rec-ensalada',
    name: 'Ensalada',
    description: 'Ensalada fresca y rápida. Ideal para gastar tomates maduros y lechuga antes de que pierdan frescura.',
    difficulty: 'Fácil',
    prep_time: 10,
    instructions: '1. Lava bien las hojas de lechuga y córtalas con las manos en trozos cómodos.\n2. Corta los tomates en gajos o dados medianos.\n3. Junta los ingredientes en una ensaladera.\n4. Aliña con aceite de oliva virgen extra, vinagre y sal justo antes de servir.',
    servings: 2,
    recipe_ingredients: [
      { ingredient_name: 'tomate' },
      { ingredient_name: 'lechuga' },
    ],
  },
  {
    id: 'rec-pasta-mediterranea',
    name: 'Pasta mediterránea',
    description: 'Pasta reconfortante al estilo mediterráneo. Aprovecha tomates frescos y queso disponible en tu nevera.',
    difficulty: 'Fácil',
    prep_time: 20,
    instructions: '1. Pon a hervir abundante agua con sal y cocina la pasta según las instrucciones del paquete.\n2. En una sartén, saltea los tomates picados en dados con una cucharada de aceite a fuego medio hasta que suelten su jugo.\n3. Escurre la pasta al dente y mézclala directamente en la sartén con el tomate.\n4. Apaga el fuego, añade el queso desmenuzado o rallado por encima y mezcla para que se funda ligeramente.',
    servings: 2,
    recipe_ingredients: [
      { ingredient_name: 'pasta' },
      { ingredient_name: 'tomate' },
      { ingredient_name: 'queso' },
    ],
  },
  {
    id: 'rec-revuelto',
    name: 'Revuelto de tomate y huevo',
    description: 'Plato exprés altamente nutritivo para salvar tomates blandos y huevos frescos.',
    difficulty: 'Fácil',
    prep_time: 12,
    instructions: '1. Trocea los tomates y saltéalos 3 minutos en una sartén con un hilo de aceite.\n2. Vierte los huevos batidos con sal.\n3. Remueve constantemente a fuego suave hasta obtener una textura cremosa.',
    servings: 2,
    recipe_ingredients: [
      { ingredient_name: 'tomate' },
      { ingredient_name: 'huevo' },
    ],
  },
  {
    id: 'rec-arroz-verduras',
    name: 'Arroz con verduras',
    description: 'Arroz de aprovechamiento para usar cualquier verdura que tengas en la nevera.',
    difficulty: 'Media',
    prep_time: 25,
    instructions: '1. Sofríe cebolla y tomate picados en una sartén.\n2. Agrega el arroz y remueve durante 2 minutos.\n3. Añade el doble de agua caliente o caldo y cocina a fuego medio 18 minutos.',
    servings: 3,
    recipe_ingredients: [
      { ingredient_name: 'arroz' },
      { ingredient_name: 'cebolla' },
      { ingredient_name: 'tomate' },
    ],
  },
  {
    id: 'rec-bol-yogur',
    name: 'Bol de Yogur con Fruta',
    description: 'Desayuno o merienda exprés ideal para consumir yogures naturales antes de su fecha de caducidad.',
    difficulty: 'Fácil',
    prep_time: 5,
    instructions: '1. Sirve el yogur en un cuenco.\n2. Añade fruta troceada o frutos secos al gusto.\n3. Opcionalmente endulza con miel.',
    servings: 1,
    recipe_ingredients: [
      { ingredient_name: 'yogur' },
    ],
  },
  {
    id: 'rec-tortilla-patatas',
    name: 'Tortilla de Patatas clásica',
    description: 'Aprovecha patatas, huevos y cebolla para preparar la clásica tortilla jugosa.',
    difficulty: 'Media',
    prep_time: 30,
    instructions: '1. Corta las patatas y la cebolla en láminas finas y póchalas en aceite abundante.\n2. Escurre el aceite y mezcla con los huevos batidos.\n3. Cuaja en la sartén a fuego medio.',
    servings: 4,
    recipe_ingredients: [
      { ingredient_name: 'patata' },
      { ingredient_name: 'huevo' },
      { ingredient_name: 'cebolla' },
    ],
  },
  {
    id: 'rec-pollo-salteado',
    name: 'Salteado de Pollo con Verduras',
    description: 'Receta rápida para cocinar pechuga de pollo con cebolla, pimientos o tomates frescos.',
    difficulty: 'Fácil',
    prep_time: 15,
    instructions: '1. Corta el pollo en tiras y dóralo en una sartén con un poco de aceite.\n2. Añade la cebolla y pimientos en juliana.\n3. Saltea a fuego vivo hasta que las verduras estén al dente.',
    servings: 2,
    recipe_ingredients: [
      { ingredient_name: 'pollo' },
      { ingredient_name: 'cebolla' },
    ],
  },
  {
    id: 'rec-crema-zanahoria',
    name: 'Crema suave de Zanahoria',
    description: 'Plato reconfortante para dar salida a zanahorias, cebollas y patatas maduras.',
    difficulty: 'Fácil',
    prep_time: 25,
    instructions: '1. Pela y trocea las zanahorias y la cebolla.\n2. Rehoga 5 minutos y cubre con agua o caldo.\n3. Hierve 20 minutos y tritura hasta obtener una textura suave.',
    servings: 3,
    recipe_ingredients: [
      { ingredient_name: 'zanahoria' },
      { ingredient_name: 'cebolla' },
    ],
  },
  {
    id: 'rec-queso-tomate',
    name: 'Tosta de Queso y Tomate',
    description: 'Aperitivo o cena ligera perfecta para aprovechar pan, queso fresco y tomates maduros.',
    difficulty: 'Fácil',
    prep_time: 8,
    instructions: '1. Tuesta rebanadas de pan.\n2. Coloca láminas de tomate maduro y queso por encima.\n3. Aliña con aceite de oliva virgen extra y orégano.',
    servings: 2,
    recipe_ingredients: [
      { ingredient_name: 'queso' },
      { ingredient_name: 'tomate' },
    ],
  },
  {
    id: 'rec-pizza-sarten',
    name: 'Pizza casera de sartén',
    description: 'Crujiente, rápida y sin necesidad de encender el horno. Ideal para calmar el antojo de pizza con lo que hay en casa.',
    difficulty: 'Fácil',
    prep_time: 15,
    instructions: '1. Mezcla harina con un poco de agua y aceite hasta formar una masa suave, o utiliza una base de pan plano.\n2. Extiende en una sartén caliente con unas gotas de aceite.\n3. Añade salsa o tomate triturado, orégano y abundante queso.\n4. Tapa la sartén a fuego medio-bajo durante 8-10 minutos hasta que la base esté crujiente y el queso fundido.',
    servings: 2,
    recipe_ingredients: [
      { ingredient_name: 'queso' },
      { ingredient_name: 'tomate' },
      { ingredient_name: 'harina' },
    ],
  },
  {
    id: 'rec-hamburguesa-clasica',
    name: 'Hamburguesa casera clásica',
    description: 'Sabrosa y jugosa. Puedes prepararla con carne picada, medallones o vegetales con cebolla dorada.',
    difficulty: 'Fácil',
    prep_time: 15,
    instructions: '1. Condimenta la carne o medallón con sal, pimienta y un toque de cebolla picada.\n2. Cocina en la sartén bien caliente 3-4 minutos por lado.\n3. Añade una loncha de queso sobre la carne en el último minuto para que se funda.\n4. Monta en pan con tomate fresco, cebolla y lechuga.',
    servings: 2,
    recipe_ingredients: [
      { ingredient_name: 'carne' },
      { ingredient_name: 'cebolla' },
      { ingredient_name: 'queso' },
      { ingredient_name: 'tomate' },
    ],
  },
  {
    id: 'rec-empanadas-criollas',
    name: 'Empanadas criollas al horno',
    description: 'Un clásico reconfortante de masa dorada con sabroso relleno de carne, cebolla y huevo duro.',
    difficulty: 'Media',
    prep_time: 30,
    instructions: '1. Pica abundante cebolla y póchala en sartén. Agrega la carne picada y condimenta con pimentón, comino y sal.\n2. Deja enfriar el relleno e incorpora huevos duros picados.\n3. Rellena las tapas de masa, realiza el repulgue y píntalas con huevo.\n4. Hornea a 200°C durante 15-20 minutos hasta que estén doradas.',
    servings: 4,
    recipe_ingredients: [
      { ingredient_name: 'cebolla' },
      { ingredient_name: 'huevo' },
      { ingredient_name: 'carne' },
    ],
  },
  {
    id: 'rec-milanesa-crocante',
    name: 'Milanesa crocante con guarnición',
    description: 'Milanesa dorada y crujiente de carne o pechuga de pollo, ideal para acompañar con ensalada o puré.',
    difficulty: 'Fácil',
    prep_time: 20,
    instructions: '1. Pasa los filetes de carne o pollo por huevo batido con sal, ajo y perejil.\n2. Rebózalos presionando firmemente en pan rallado.\n3. Cocina en horno fuerte con unas gotas de aceite o fríe hasta que queden doradas y crocantes.\n4. Sirve caliente con gajos de limón y ensalada fresca.',
    servings: 2,
    recipe_ingredients: [
      { ingredient_name: 'pollo' },
      { ingredient_name: 'huevo' },
      { ingredient_name: 'pan' },
    ],
  },
  {
    id: 'rec-roll-vegetariano',
    name: 'Roll vegetariano',
    description: 'Inspirado en sushi tradicional. Rollos frescos envueltos con arroz sazonado, zanahoria y vegetales crocantes.',
    difficulty: 'Media',
    prep_time: 25,
    instructions: '1. Cocina arroz de grano corto y condiméntalo con unas gotas de vinagre, sal y un toque de azúcar.\n2. Corta zanahoria, pepino o lechuga en bastones finos.\n3. Extiende el arroz sobre alga nori o film, añade los vegetales en el centro y enrolla con firmeza.\n4. Corta en bocados con cuchillo humedecido y sirve con salsa de soja.',
    servings: 2,
    recipe_ingredients: [
      { ingredient_name: 'arroz' },
      { ingredient_name: 'zanahoria' },
      { ingredient_name: 'lechuga' },
    ],
  },
  {
    id: 'rec-bol-arroz-oriental',
    name: 'Bol de arroz oriental',
    description: 'Todo el sabor del sushi en un cuenco rápido sin complicaciones. Arroz sazonado con huevo, verduras y soja.',
    difficulty: 'Fácil',
    prep_time: 15,
    instructions: '1. Sirve una base de arroz blanco caliente en un bol amplio.\n2. Corona con huevo poché o revuelto suave, zanahoria rallada y cebolla salteada.\n3. Aliña con un toque de salsa de soja, aceite y semillas de sésamo.',
    servings: 1,
    recipe_ingredients: [
      { ingredient_name: 'arroz' },
      { ingredient_name: 'huevo' },
      { ingredient_name: 'zanahoria' },
      { ingredient_name: 'cebolla' },
    ],
  },
  {
    id: 'rec-onigiri-sencillo',
    name: 'Onigiri sencillo',
    description: 'Triángulos de arroz tradicionales japoneses. Fáciles de moldear a mano con un corazón sabroso.',
    difficulty: 'Fácil',
    prep_time: 15,
    instructions: '1. Con las manos humedecidas y con sal, toma una porción de arroz tibio.\n2. Coloca en el centro un relleno de pollo, atún o queso.\n3. Modela suavemente formando un triángulo compacto y decora con sésamo o alga.',
    servings: 2,
    recipe_ingredients: [
      { ingredient_name: 'arroz' },
      { ingredient_name: 'pollo' },
    ],
  },
  {
    id: 'rec-ensalada-japonesa',
    name: 'Ensalada japonesa',
    description: 'Acompañamiento clásico de los restaurantes de sushi. Hojas verdes crocantes con aderezo sutil de zanahoria y soja.',
    difficulty: 'Fácil',
    prep_time: 10,
    instructions: '1. Lava y trocea lechuga y vegetales frescos.\n2. Ralla zanahoria finamente e incorpórala a la ensaladera.\n3. Prepara una vinagreta ligera con vinagre, unas gotas de aceite y soja.\n4. Mezcla antes de servir para mantener la máxima frescura.',
    servings: 2,
    recipe_ingredients: [
      { ingredient_name: 'lechuga' },
      { ingredient_name: 'zanahoria' },
      { ingredient_name: 'tomate' },
    ],
  },
]
