import type { LocalRecipe } from './initialRecipes'

/**
 * Biblioteca culinaria de platos tradicionales de países limítrofes y de la región
 * (Uruguay, Chile, Paraguay, Bolivia, Brasil y Perú), adaptados para elaborarse con
 * ingredientes habituales en cocinas locales y despensas familiares.
 *
 * Basados en preparaciones populares de plataformas de cocina comunitaria tipo Cookpad,
 * con diversos grados de dificultad (Fácil, Media, Difícil) y fichas de elaboración extendidas.
 */
export const NEIGHBORING_COUNTRY_RECIPES: LocalRecipe[] = [
  // ==========================================
  // --- URUGUAY 🇺🇾 ---
  // ==========================================
  {
    id: 'cat-uy-chivito-al-pan',
    name: 'Chivito uruguayo completo al pan',
    description: 'El sándwich emblema de la gastronomía charrúa: tierno lomo a la plancha con jamón, queso derretido, panceta crocante, huevo y vegetales.',
    difficulty: 'Fácil',
    prep_time: 20,
    instructions: '1. Sella el bife de lomo en plancha muy caliente 2 minutos por lado con sal.\n2. En la misma plancha dora panceta y derrite el queso sobre el jamón.\n3. Cocina un huevo a la plancha dejando la yema jugosa.\n4. Tuesta el pan, úntalo con mayonesa suave, dispone lechuga y tomate en rodajas.\n5. Corona con la carne, el queso fundido, panceta y el huevo.',
    servings: 2,
    recipe_ingredients: [
      { ingredient_name: 'carne' },
      { ingredient_name: 'queso' },
      { ingredient_name: 'huevo' },
      { ingredient_name: 'pan' },
      { ingredient_name: 'tomate' },
      { ingredient_name: 'lechuga' },
    ],
    origin: 'Uruguay 🇺🇾',
    chef_tips: 'El bife de lomo debe ser fino para cocinarse en pocos minutos sin secarse. Montar el queso directamente sobre el corte recién salido del fuego para que se funda con el calor residual.',
    detailed_steps: [
      'Corte de carne: Filetear el bife de lomo o cuadril en láminas de 1 cm y aplanar suavemente.',
      'Cocción viva: Calentar la plancha o sartén de hierro con unas gotas de aceite; sellar 90 segundos por lado.',
      'Fundido charrúa: Apilar sobre la carne caliente una feta de jamón y una lámina gruesa de queso mozzarella o cuartirolo para fundir.',
      'Huevo y panceta: Cocinar el huevo con borde crocante y la panceta dorada en paralelo.',
      'Montaje al pan: Armar en pan tortuga o francés tostado con lechuga mantecosa, rodajas finas de tomate y mayonesa.',
    ],
    substitutes: 'Si no tienes lomo, utiliza nalga, bife de chorizo o pechuga de pollo cortada en filetes delgados.',
    pairing: 'Papas fritas bastón caseras y cerveza rubia bien helada.',
  },
  {
    id: 'cat-uy-pamplonas-pollo',
    name: 'Pamplonas de pollo uruguayas a la plancha',
    description: 'Arrollados rústicos uruguayos rellenos de queso derretido, jamón, morrón asado y panceta, sellados a fuego dorado.',
    difficulty: 'Media',
    prep_time: 35,
    instructions: '1. Abre las pechugas de pollo en mariposa y aplana con film.\n2. Rellena el centro con queso cremoso, tiras de morrón y jamón.\n3. Enrolla firmemente y envuelve por fuera con panceta o papel manteca/aluminio.\n4. Cocina en sartén o plancha a fuego medio-bajo durante 25 minutos girando cada 6 minutos hasta dorar pareja y cocer el interior.',
    servings: 3,
    recipe_ingredients: [
      { ingredient_name: 'pollo' },
      { ingredient_name: 'queso' },
      { ingredient_name: 'morron' },
      { ingredient_name: 'panceta' },
    ],
    origin: 'Uruguay 🇺🇾',
    chef_tips: 'Atar con hilo de cocina o sujetar con palillos de madera para que el queso fundido no escape durante la cocción.',
    detailed_steps: [
      'Apertura del pollo: Desgrasar las pechugas y abrirlas en libro asegurando un grosor uniforme de 1 cm.',
      'Condimentación: Frotar con sal entrefina, pimienta negra molida y una pizca de orégano seco.',
      'Carga del relleno: Disponer bastones de queso firme, morrón rojo salteado o en conserva y panceta.',
      'Envoltura: Enrollar ajustado como un cilindro y sujetar firmemente.',
      'Dorado parejo: Cocinar despacio con tapa a fuego moderado para asegurar cocción completa hasta el centro.',
    ],
    substitutes: 'Se puede sustituir el pollo por lomo de cerdo o solomillo abierto fino.',
    pairing: 'Ensalada criolla de tomate y cebolla o puré de papas con nuez moscada.',
  },
  {
    id: 'cat-uy-pascualina-uruguaya',
    name: 'Torta pascualina uruguaya hojaldrada',
    description: 'Clásico de panaderías y mesas familiares de Montevideo: doble masa crocante con relleno de acelga o espinaca, queso rallado y huevos enteros horneados.',
    difficulty: 'Media',
    prep_time: 40,
    instructions: '1. Saltea acelga o espinaca escurrida con cebolla picada y nuez moscada.\n2. Mezcla con abundante queso rallado y 1 huevo batido para amalgamar.\n3. Vierte sobre molde forrado con masa.\n4. Haz 4 huecos en el relleno y rompe huevos crudos enteros dentro.\n5. Cubre con la tapa de masa, pincha con tenedor y hornea 30 minutos a 190°C.',
    servings: 4,
    recipe_ingredients: [
      { ingredient_name: 'acelga' },
      { ingredient_name: 'queso' },
      { ingredient_name: 'huevo' },
      { ingredient_name: 'cebolla' },
      { ingredient_name: 'harina' },
    ],
    origin: 'Uruguay 🇺🇾',
    chef_tips: 'Es indispensable exprimir muy bien la verdura cocida con un paño limpio para retirar el exceso de agua y evitar que humedezca la base.',
    detailed_steps: [
      'Cocción verde: Blanquear la acelga 3 minutos en agua hirviendo con sal, escurrir y picar grueso.',
      'Sofrito dulce: Pochar cebolla en manteca o aceite hasta traslúcida y mezclar con la verdura.',
      'Ligazón: Añadir queso rallado reggianito o sardo y una pizca de nuez moscada.',
      'Nidos de huevo: Ahuecar la superficie del relleno y colocar los huevos enteros.',
      'Horneado dorado: Pincelar con huevo batido y cocinar a 190°C hasta que la masa quede crujiente y dorada.',
    ],
    substitutes: 'Puedes mezclar espinaca fresca con ricota suave para un resultado aún más cremoso.',
    pairing: 'Infusión tibia o copa de vino blanco joven.',
  },
  {
    id: 'cat-uy-martin-fierro',
    name: 'Postre Martín Fierro criollo tradicional',
    description: 'El postre de taberna y pulpería por excelencia: maridaje armónico de queso colonia o cuartirolo con dulce de membrillo o batata.',
    difficulty: 'Fácil',
    prep_time: 5,
    instructions: '1. Corta rebanadas rectangulares parejas de queso semicurado o cuartirolo firme.\n2. Corta láminas de dulce de membrillo o batata del mismo grosor.\n3. Superpón ambas capas en plato de postre.\n4. Decora con nueces picadas si deseas un toque crocante.',
    servings: 2,
    recipe_ingredients: [
      { ingredient_name: 'queso' },
      { ingredient_name: 'dulce de membrillo' },
    ],
    origin: 'Uruguay 🇺🇾',
    chef_tips: 'Servir a temperatura ambiente templada para que el queso exprese toda su cremosidad y aroma láctico.',
    detailed_steps: [
      'Selección de piezas: Emplear queso de pasta semidura tipo Colonia, Mar del Plata o cuartirolo estacionado.',
      'Geometría: Cortar bloques de 1 cm de espesor para lograr el balance justo entre dulce y salado.',
      'Presentación: Alternar en abanico o servir en torre prolija.',
    ],
    substitutes: 'Si no tienes dulce de membrillo, sustituye por dulce de batata con chocolate o mermelada densa.',
    pairing: 'Café expreso recién tostado o té negro con cáscara de naranja.',
  },

  // ==========================================
  // --- CHILE 🇨🇱 ---
  // ==========================================
  {
    id: 'cat-cl-pastel-de-choclo',
    name: 'Pastel de choclo tradicional chileno',
    description: 'Banquete campesino chileno: base de pino de carne molida sazonada con comino y cebolla, trozos de pollo dorado, aceitunas y cubierta cremosa de choclo caramelizado.',
    difficulty: 'Difícil',
    prep_time: 55,
    instructions: '1. Prepara el pino: cocina carne picada con cebolla en cubos, comino, ají de color y sal hasta que esté jugoso.\n2. En licuadora o procesadora procesa el choclo con leche, manteca y hojas de albahaca fresca.\n3. Cocina la pasta de choclo en olla a fuego medio removiendo hasta que espese y cambie a amarillo brillante.\n4. En fuente para horno coloca una base generosa de pino, trozos de pollo cocido y huevo duro picado.\n5. Cubre con la pastelera de choclo, espolvorea azúcar encima y hornea a 210°C hasta gratinar dorado.',
    servings: 4,
    recipe_ingredients: [
      { ingredient_name: 'choclo' },
      { ingredient_name: 'carne' },
      { ingredient_name: 'pollo' },
      { ingredient_name: 'cebolla' },
      { ingredient_name: 'huevo' },
      { ingredient_name: 'leche' },
    ],
    origin: 'Chile 🇨🇱',
    chef_tips: 'El secreto chileno es el toque de hojas de albahaca fresca licuadas junto con el choclo, y el azúcar espolvoreado en la superficie para formar costra caramelizada.',
    detailed_steps: [
      'Elaboración del pino: Cocinar cebolla lentamente para que no repita; incorporar la carne picada con comino abundante y dejar reposar.',
      'Pastelera de choclo: Desgranar choclos tiernos y procesar con chorrito de leche y albahaca.',
      'Cocción de la crema: Cocinar en olla 10 minutos revolviendo con cuchara de madera hasta que brille.',
      'Armado en greda: Colocar el pino en la base de cazuelas de barro, sumar pollo dorado y huevo duro.',
      'Gratinado: Verter la pastelera, espolvorear azúcar común y llevar a horno fuerte 20 minutos.',
    ],
    substitutes: 'Si no consigues choclo fresco en mazorca, puedes usar choclo en lata escurrido combinado con harina de maíz fina para espesar.',
    pairing: 'Ensalada chilena de tomate con cebolla amortiguada en pluma y vino tinto Carménère o Malbec.',
  },
  {
    id: 'cat-cl-charquican-casero',
    name: 'Charquicán chileno casero con huevo frito',
    description: 'Guiso tradicional reconfortante de zapallo tierno, papas, carne y choclo machacados a mano, coronado con huevo a caballo.',
    difficulty: 'Fácil',
    prep_time: 30,
    instructions: '1. Hierve en agua con sal cubos de papa y zapallo hasta que estén tiernos.\n2. En sartén dora carne picada con cebolla, morrón y comino.\n3. Agrega choclo en granos al sofrito de carne.\n4. Incorpora las papas y el zapallo cocidos con un cucharón de su caldo y machaca rústicamente con pisapapas.\n5. Sirve humeante coronado con un huevo frito de yema tierna.',
    servings: 3,
    recipe_ingredients: [
      { ingredient_name: 'papa' },
      { ingredient_name: 'zapallo' },
      { ingredient_name: 'carne' },
      { ingredient_name: 'choclo' },
      { ingredient_name: 'cebolla' },
      { ingredient_name: 'huevo' },
    ],
    origin: 'Chile 🇨🇱',
    chef_tips: 'No tritures con minipimer ni procesadora: la textura auténtica del charquicán debe ser rústica, donde se sientan trozos de zapallo y papas amalgamados.',
    detailed_steps: [
      'Hervido de tubérculos: Cortar zapallo plomo o calabaza y papas en dados iguales de 2 cm; cocer 15 minutos.',
      'Sofrito sabroso: Sofreír cebolla picada fina con ajo y ají de color; añadir la carne picada y dorar.',
      'Unión: Verter las verduras cocidas escurridas en la sartén del sofrito.',
      'Machacado: Aplastar con pisapapas manteniendo tropezones tiernos.',
      'Toque final: Freír los huevos con puntilla dorada y montar sobre cada plato hondo.',
    ],
    substitutes: 'Puedes agregar porotos verdes picados finos o arvejas para enriquecer el color.',
    pairing: 'Pebre fresco con cilantro picado y pan amasado tibio.',
  },
  {
    id: 'cat-cl-tomatican-carne',
    name: 'Tomaticán chileno de carne y choclo tierno',
    description: 'Guiso campestre rápido y jugoso elaborado con tiras de carne, tomates maduros deshechos en su jugo y granos dulces de choclo.',
    difficulty: 'Fácil',
    prep_time: 25,
    instructions: '1. Corta carne en tiras delgadas y sella a fuego vivo en sartén con aceite.\n2. Agrega cebolla en pluma y rehoga hasta transparentar.\n3. Suma abundante tomate pelado picado y granos de choclo con orégano y comino.\n4. Cocina tapado 12 minutos a fuego suave hasta que el tomate forme una salsa untuosa.\n5. Sirve con arroz blanco o papas al vapor.',
    servings: 2,
    recipe_ingredients: [
      { ingredient_name: 'carne' },
      { ingredient_name: 'tomate' },
      { ingredient_name: 'choclo' },
      { ingredient_name: 'cebolla' },
    ],
    origin: 'Chile 🇨🇱',
    chef_tips: 'Aprovecha tomates bien maduros de verano que aportan todo el jugo necesario sin tener que agregar agua artificial.',
    detailed_steps: [
      'Corte de ingredientes: Cortar la carne en tiras tipo fajita y la cebolla en juliana fina.',
      'Sellado: Dorar la carne en tandas para concentrar los jugos.',
      'Guisado: Incorporar los tomates troceados con piel o pelados y el choclo.',
      'Sazón: Rectificar sal, pimienta negra molida y orégano seco.',
    ],
    substitutes: 'Queda excelente reemplazando la carne vacuna por cubos de pechuga de pollo.',
    pairing: 'Arroz blanco con ajo dorado o pan crujiente para mojar la salsa.',
  },
  {
    id: 'cat-cl-cazuela-vacuno',
    name: 'Cazuela chilena de vacuno y zapallo camote',
    description: 'Caldo de fiesta dominguera con trozo de osobuco o costillar, trozo entero de zapallo, choclo con coronta y papas tiernas.',
    difficulty: 'Media',
    prep_time: 45,
    instructions: '1. Sella los trozos de carne con cebolla, morrón y zanahoria en olla grande.\n2. Cubre con 1.5 litros de agua y cocina 25 minutos espumando impurezas.\n3. Agrega papas enteras peladas, trozos de zapallo y choclo en ruedas.\n4. Suma un puñado de arroz y porotos verdes si tienes a mano.\n5. Cocina 15 minutos más hasta que la verdura esté suave. Sirve cada plato con una porción de cada vegetal.',
    servings: 4,
    recipe_ingredients: [
      { ingredient_name: 'carne' },
      { ingredient_name: 'zapallo' },
      { ingredient_name: 'papa' },
      { ingredient_name: 'choclo' },
      { ingredient_name: 'arroz' },
      { ingredient_name: 'cebolla' },
      { ingredient_name: 'zanahoria' },
    ],
    origin: 'Chile 🇨🇱',
    chef_tips: 'Cocinar a hervor suave sin borbotones violentos para mantener un caldo transparente, limpio y profundamente aromático.',
    detailed_steps: [
      'Base de olla: Dorar la carne con hueso (osobuco o asado de tira) con cebolla y orégano.',
      'Extracción de sabor: Hervir despacio para que el colágeno del hueso enriquezca el caldo.',
      'Tiempos de vegetales: Incorporar papas y choclo primero, y el zapallo los últimos 10 minutos para que no se desarme.',
      'Final aromático: Espolvorear perejil fresco o cilantro recién picado al servir.',
    ],
    substitutes: 'Se puede preparar cazuela de pollo siguiendo exactamente los mismos pasos.',
    pairing: 'Pebre picante con ají verde y vino tinto.',
  },
  {
    id: 'cat-cl-porotos-con-riendas',
    name: 'Porotos con riendas tradicionales chilenos',
    description: 'Clásico invernal de porotos cocidos a fuego lento con fideos tallarines (riendas), zapallo pisado cremoso y chorizo dorado.',
    difficulty: 'Media',
    prep_time: 40,
    instructions: '1. Cocina porotos remojados con zapallo en cubos hasta que estén tiernos.\n2. Pisa parte del zapallo en el mismo caldo para otorgar consistencia espesa.\n3. Agrega fideos tallarines partidos al medio y cocina 8 minutos.\n4. En sartén prepara un sofrito de cebolla con ají de color y rodajas de chorizo.\n5. Vierte el sofrito sobre los porotos hirviendo y cocina 2 minutos más antes de servir.',
    servings: 4,
    recipe_ingredients: [
      { ingredient_name: 'porotos' },
      { ingredient_name: 'fideos' },
      { ingredient_name: 'zapallo' },
      { ingredient_name: 'cebolla' },
      { ingredient_name: 'chorizo' },
    ],
    origin: 'Chile 🇨🇱',
    chef_tips: 'El zapallo pisado dentro del caldo es el elemento clave para ligar los porotos y crear la textura aterciopelada tradicional.',
    detailed_steps: [
      'Cocción base: Cocer los porotos con el zapallo en abundante agua con sal.',
      'Textura: Con cuchara de madera, aplastar el zapallo contra el costado de la olla.',
      'Las riendas: Partir los tallarines en tres partes y añadirlos al caldo.',
      'El sofrito colorado: Dorar cebolla picada con manteca y pimentón dulce/ají de color.',
      'Emulsión: Integrar todo y reposar 5 minutos antes de emplatar.',
    ],
    substitutes: 'Puedes usar porotos en lata enjuagados para reducir el tiempo de cocción a 20 minutos.',
    pairing: 'Ensalada de repollo crujiente con limón y aceite de oliva.',
  },

  // ==========================================
  // --- PARAGUAY 🇵🇾 ---
  // ==========================================
  {
    id: 'cat-py-sopa-paraguaya',
    name: 'Sopa paraguaya tradicional al horno',
    description: 'La única sopa sólida del mundo: esponjoso pastel salado a base de harina de maíz, abundante queso cremoso derretido, cebolla pochada y leche.',
    difficulty: 'Fácil',
    prep_time: 35,
    instructions: '1. Pocha abundante cebolla cortada en juliana fina en sartén con aceite y sal hasta que esté muy blanda.\n2. En un bol bate los huevos, incorpora la leche y la cebolla pochada con su aceite.\n3. Agrega la harina de maíz (o polenta fina) en forma de lluvia batiendo para evitar grumos.\n4. Incorpora queso en dados generosos y sal fina.\n5. Vierte en asadera engrasada y hornea a 190°C durante 30 minutos hasta dorar la cubierta.',
    servings: 4,
    recipe_ingredients: [
      { ingredient_name: 'harina de maiz' },
      { ingredient_name: 'queso' },
      { ingredient_name: 'cebolla' },
      { ingredient_name: 'huevo' },
      { ingredient_name: 'leche' },
    ],
    origin: 'Paraguay 🇵🇾',
    chef_tips: 'Pochar la cebolla despacio con una pizca de sal sin que tome color oscuro para que quede dulce y jugosa.',
    detailed_steps: [
      'Pochar la cebolla: Cocinar a fuego bajo 10 minutos con aceite o manteca.',
      'Mezcla líquida: Batir huevos con leche entera hasta espumar.',
      'Harina de maíz: Emplear harina de maíz paraguaya o polenta de cocción rápida tamizada.',
      'Queso abundante: Cortar queso cuartirolo, mar del plata o cremoso en dados medianos.',
      'Cocción en placa: Esparcir en asadera aceitada formando una capa de 3 a 4 cm de alto; hornear hasta dorar.',
    ],
    substitutes: 'Si no tienes harina de maíz paraguaya, utiliza polenta instantánea o choclo procesado fino.',
    pairing: 'Carne asada a la parrilla, mandioca hervida caliente y mate cocido.',
  },
  {
    id: 'cat-py-chipa-guazu',
    name: 'Chipa Guazú cremoso al horno',
    description: 'Tarta húmeda y deliciosa de choclo fresco desgranado, queso fundente, cebolla salteada, huevos y leche.',
    difficulty: 'Fácil',
    prep_time: 35,
    instructions: '1. Rehoga la cebolla picada con manteca o aceite hasta que esté transparente.\n2. Procesa la mitad de los granos de choclo con leche y huevos, y deja la otra mitad entera para dar textura.\n3. Mezcla en un bol el choclo licuado con los granos enteros, la cebolla salteada y queso en dados.\n4. Vierte en fuente enmantecada.\n5. Hornea a 190°C durante 30 minutos hasta que quede firme y gratinado.',
    servings: 4,
    recipe_ingredients: [
      { ingredient_name: 'choclo' },
      { ingredient_name: 'queso' },
      { ingredient_name: 'cebolla' },
      { ingredient_name: 'huevo' },
      { ingredient_name: 'leche' },
    ],
    origin: 'Paraguay 🇵🇾',
    chef_tips: 'Mantener la mitad del choclo entero y la otra mitad procesada crea el contraste perfecto entre cremosidad y bocado.',
    detailed_steps: [
      'Desgranar choclo: Emplear mazorcas de choclo amarillo dulce desgranadas.',
      'Licuado húmedo: Procesar con los huevos y la leche hasta formar una crema rústica.',
      'Añadir queso: Usar queso paraguay o queso cremoso blando bien distribuido.',
      'Horneado suave: Cocinar hasta que al pinchar con un cuchillo salga limpio y la superficie esté dorada.',
    ],
    substitutes: 'Puedes emplear choclo en lata o congelado escurriéndolo bien previamente.',
    pairing: 'Asado a la estaca o ensalada de hojas verdes frescas con limón.',
  },
  {
    id: 'cat-py-mbeju-crocante',
    name: 'Mbejú paraguayo tradicional crocante',
    description: 'Torta delgada y tostada en sartén de almidón de mandioca, queso criollo y manteca, crocante por fuera y suave por dentro.',
    difficulty: 'Fácil',
    prep_time: 15,
    instructions: '1. En un bol mezcla almidón de mandioca con sal y manteca en pomada.\n2. Desmenuza con los dedos hasta formar un arenado húmedo.\n3. Incorpora el queso desgranado y rocía unas gotas de leche.\n4. Vierte una porción en sartén caliente sin aceite ni manteca.\n5. Aplana con espátula los bordes y cocina 3 minutos por lado hasta que dore con manchas tostadas.',
    servings: 2,
    recipe_ingredients: [
      { ingredient_name: 'almidon de mandioca' },
      { ingredient_name: 'queso' },
      { ingredient_name: 'manteca' },
      { ingredient_name: 'leche' },
    ],
    origin: 'Paraguay 🇵🇾',
    chef_tips: 'No amasar: la mezcla debe parecer arena gruesa húmeda. En la sartén se une sola con el calor del queso.',
    detailed_steps: [
      'Arenado: Frotar el almidón con la manteca entre las palmas de las manos.',
      'Hidratación mínima: Salpicar con una cucharada de leche sólo para humedecer.',
      'Sartén ardiente: Utilizar sartén de hierro o teflón bien caliente.',
      'Sellado: Presionar ligeramente los bordes para redondear; dar vuelta con plato.',
    ],
    substitutes: 'Si no consigues almidón de mandioca puro, combina mitad de maicena con harina de trigo.',
    pairing: 'Cocido quemado con leche o café con leche espumoso.',
  },
  {
    id: 'cat-py-vori-vori-pollo',
    name: 'Vorí Vorí de pollo paraguayo',
    description: 'Sopa-guiso distinguida de la cocina guaraní: caldo sustancioso de pollo con verduras y delicadas bolitas de harina de maíz y queso.',
    difficulty: 'Media',
    prep_time: 40,
    instructions: '1. Dora trozos de pollo en olla con cebolla, morrón, zanahoria y ajo.\n2. Cubre con 1.5 litros de agua y hierve 20 minutos para lograr caldo sabroso.\n3. En un bol prepara los vorí-vorí: mezcla harina de maíz con queso rallado y unas cucharadas de caldo caliente hasta formar masa moldeable.\n4. Haz bolitas del tamaño de una nuez y arrójalas al caldo hirviendo.\n5. Cocina 10 minutos más hasta que las bolitas floten y estén suaves.',
    servings: 4,
    recipe_ingredients: [
      { ingredient_name: 'pollo' },
      { ingredient_name: 'harina de maiz' },
      { ingredient_name: 'queso' },
      { ingredient_name: 'cebolla' },
      { ingredient_name: 'morron' },
      { ingredient_name: 'zanahoria' },
    ],
    origin: 'Paraguay 🇵🇾',
    chef_tips: 'Las bolitas de vorí-vorí deben moldearse húmedas para que no se desarmen al entrar en el caldo hirviendo.',
    detailed_steps: [
      'Dorado de presas: Sellar muslos o pechugas con piel para extraer todo el sabor.',
      'Mirepoix criollo: Rehogar verduras con una pizca de orégano y comino.',
      'Amasado de bolitas: Unir harina de maíz con queso sardo o criollo usando el propio caldo tibio.',
      'Cocción: Introducir una a una en el caldo en ebullición suave.',
    ],
    substitutes: 'Puedes elaborar vorí-vorí de carne vacuna sustituyendo el pollo por osobuco o aguja.',
    pairing: 'Mandioca hervida al vapor con sal gruesa.',
  },
  {
    id: 'cat-py-bife-koyigua',
    name: 'Bife Koyigua paraguayo encebollado con huevo',
    description: 'Bifes tiernos estofados tapados bajo una cúpula de cebollas dulces, tomate triturado y huevos escalfados en la misma salsa.',
    difficulty: 'Fácil',
    prep_time: 20,
    instructions: '1. Sella los bifes en sartén amplia con aceite a fuego fuerte 2 minutos por lado.\n2. Baja el fuego y cubre los bifes con abundante cebolla en aros y tomates picados.\n3. Tapa la sartén para que la verdura suelte sus jugos y cocine la carne al vapor 10 minutos.\n4. Abre huecos en la verdura y rompe huevos enteros encima.\n5. Tapa 3 minutos hasta que la clara cuaje y la yema quede cremosa.',
    servings: 2,
    recipe_ingredients: [
      { ingredient_name: 'carne' },
      { ingredient_name: 'cebolla' },
      { ingredient_name: 'tomate' },
      { ingredient_name: 'huevo' },
    ],
    origin: 'Paraguay 🇵🇾',
    chef_tips: 'Cocinar siempre con la sartén tapada para que el jugo de la cebolla y el tomate cocine los huevos al vapor sin secar los bifes.',
    detailed_steps: [
      'Elección de carne: Usar bife de nalga, cuadril o bola de lomo salpimentado.',
      'Cama de vegetales: Disponer capas alternadas de cebolla y tomate fresco.',
      'Cocción estofada: Reducir fuego y tapar herméticamente.',
      'Huevos al nido: Colocar los huevos justo antes de retirar del fuego.',
    ],
    substitutes: 'Queda espectacular también con filetes de merluza o pechuga de pollo.',
    pairing: 'Arroz blanco con manteca o mandioca recién hervida.',
  },

  // ==========================================
  // --- BOLIVIA 🇧🇴 ---
  // ==========================================
  {
    id: 'cat-bo-silpancho-cochabambino',
    name: 'Silpancho cochabambino tradicional',
    description: 'Emblemático plato boliviano: milanesa gigante y finísima de carne aplastada con pan rallado sobre cama de arroz y papas doradas, huevo frito y llajwa fresca.',
    difficulty: 'Media',
    prep_time: 30,
    instructions: '1. Coloca el bife de carne sobre una tabla con abundante pan rallado y golpea con mazo o palo hasta dejarlo del grosor de una hoja.\n2. Fríe la carne a fuego vivo 1 minuto por lado para que quede crocante y dorada.\n3. En el plato sirve una base de arroz blanco y papas cocidas doradas en sartén.\n4. Coloca la carne gigante encima, corona con 2 huevos fritos y salsa de tomate y cebolla picada fina.',
    servings: 2,
    recipe_ingredients: [
      { ingredient_name: 'carne' },
      { ingredient_name: 'papa' },
      { ingredient_name: 'arroz' },
      { ingredient_name: 'huevo' },
      { ingredient_name: 'tomate' },
      { ingredient_name: 'cebolla' },
      { ingredient_name: 'pan' },
    ],
    origin: 'Bolivia 🇧🇴',
    chef_tips: 'Golpear la carne con el pan rallado sobre ambos lados para integrarlo en las fibras de la carne; se debe estirar hasta cubrir el tamaño de un plato grande.',
    detailed_steps: [
      'Aplanado de carne: Colocar carne magra entre capas de pan rallado y machacar con fuerza hasta doblar su diámetro.',
      'Guarnición doble: Hervir papas en rodajas y dorarlas en manteca; cocer arroz blanco con ajo.',
      'Fritura relámpago: Freír la carne en aceite bien caliente durante apenas 60 segundos por cara.',
      'Montaje de pisos: Arroz + papas doradas + carne crocante + huevo frito + salsa fresca de tomate y cebolla picada.',
    ],
    substitutes: 'Puedes utilizar carne picada magra moldeada y estirada con pan rallado.',
    pairing: 'Salsa llajwa picante de tomate con locoto/ají y bebida fresca de frutas.',
  },
  {
    id: 'cat-bo-pique-macho',
    name: 'Pique Macho cochabambino con papas fritas',
    description: 'Festín boliviano para compartir: trozos jugosos de carne de res salteada con chorizo o salchichas, cebolla, morrón y tomate, servidos sobre papas fritas crocantes y huevo duro.',
    difficulty: 'Media',
    prep_time: 30,
    instructions: '1. Corta carne vacuna en dados medianos y chorizo en rodajas.\n2. Saltea la carne y el chorizo en sartén amplia a fuego alto con ajo y comino.\n3. Incorpora cebolla y morrón en tiras gruesas y tomates en gajos; saltea 4 minutos manteniendo jugosidad.\n4. Sirve una fuente con papas fritas crocantes en la base.\n5. Vierte la carne salteada caliente con su jugo sobre las papas y decora con rodajas de huevo duro.',
    servings: 3,
    recipe_ingredients: [
      { ingredient_name: 'carne' },
      { ingredient_name: 'chorizo' },
      { ingredient_name: 'papa' },
      { ingredient_name: 'morron' },
      { ingredient_name: 'cebolla' },
      { ingredient_name: 'tomate' },
      { ingredient_name: 'huevo' },
    ],
    origin: 'Bolivia 🇧🇴',
    chef_tips: 'El salteado debe conservar abundante jugo sabroso en el fondo de la sartén, que humedece deliciosamente las papas fritas sin quitarles la crocancia.',
    detailed_steps: [
      'Corte parejo: Picar lomo o cuadril en bocados de 2 cm; cortar salchichas o chorizos parrillero en rodajas.',
      'Salteado a fuego fuerte: Sellar la carne primero, sumar embutidos y desglasar con chorrito de cerveza o caldo.',
      'Verduras al dente: Añadir cebolla y morrón para que conserven textura crujiente.',
      'Armado en fuente: Colchón de papas fritas recién sacadas, vertido del salteado caliente y coronación con huevo duro.',
    ],
    substitutes: 'Puedes agregar tiras de pechuga de pollo junto a la carne vacuna.',
    pairing: 'Cerveza rubia fría y ají picante al gusto.',
  },
  {
    id: 'cat-bo-sopa-de-mani',
    name: 'Sopa de maní boliviana tradicional con carne',
    description: 'Sopa nutritiva y reconfortante de Cochabamba: caldo suave espesado con maní tostado licuado, carne tierna, verduras y fideos tostados crocantes.',
    difficulty: 'Media',
    prep_time: 45,
    instructions: '1. Tuesta fideos secos en sartén seca hasta que tomen color dorado oscuro.\n2. En olla hierve carne vacuna o pollo en agua con zanahoria, cebolla y orégano.\n3. Licua maní pelado con agua hasta lograr una pasta blanca cremosa y homogénea.\n4. Vierte el maní licuado a la olla y cocina a fuego suave 25 minutos revolviendo ocasionalmente.\n5. Agrega papas en cubos y los fideos tostados los últimos 10 minutos. Sirve caliente con perejil fresco.',
    servings: 4,
    recipe_ingredients: [
      { ingredient_name: 'carne' },
      { ingredient_name: 'papa' },
      { ingredient_name: 'fideos' },
      { ingredient_name: 'zanahoria' },
      { ingredient_name: 'cebolla' },
      { ingredient_name: 'mani' },
    ],
    origin: 'Bolivia 🇧🇴',
    chef_tips: 'Tostar los fideos en seco antes de hervirlos es el gran secreto boliviano: aporta sabor a nuez y evita que la pasta se ablande de más.',
    detailed_steps: [
      'Tostado de fideos: Tostar fideos cinta o coditos a fuego moderado en sartén hasta color avellana.',
      'Pasta de maní: Procesar maní sin sal con agua tibia hasta emulsión sedosa.',
      'Cocción lenta: Hervir el caldo con la pasta de maní para que espese con textura de crema suave.',
      'Incorporación final: Agregar las papas y los fideos tostados hasta su punto justo.',
    ],
    substitutes: 'Si no tienes maní entero, puedes usar una cucharada colmada de mantequilla de maní 100% natural sin azúcar diluida en caldo.',
    pairing: 'Pan marraqueta o pan casero crujiente y perejil fresco picado.',
  },
  {
    id: 'cat-bo-majadito-cruceno',
    name: 'Majadito cruceño de pollo con arroz',
    description: 'Plato tradicional de Santa Cruz de la Sierra: arroz cremoso y amarillo cocido con carne o pollo desmenuzado, morrón, cebolla, huevo frito y plátano/banana frita.',
    difficulty: 'Fácil',
    prep_time: 30,
    instructions: '1. Hierve pollo en agua con sal y desmenúzalo con tenedor.\n2. En cacerola dora cebolla, morrón picado, ajo y pimentón o cúrcuma.\n3. Agrega el pollo desmenuzado y el arroz; saltea 2 minutos.\n4. Vierte el caldo caliente del pollo y cocina hasta que el arroz esté tierno y húmedo.\n5. Sirve caliente acompañado con huevo frito y rodajas de banana doradas en manteca.',
    servings: 3,
    recipe_ingredients: [
      { ingredient_name: 'pollo' },
      { ingredient_name: 'arroz' },
      { ingredient_name: 'cebolla' },
      { ingredient_name: 'morron' },
      { ingredient_name: 'huevo' },
    ],
    origin: 'Bolivia 🇧🇴',
    chef_tips: 'El majadito puede servirse seco o tostado (majado tostado), pero la versión húmeda (majado batido) es especialmente reconfortante para una comida rápida.',
    detailed_steps: [
      'Desmenuzado de ave: Cocinar pechuga o muslo y desmechar en fibras largas.',
      'Base colorada: Sofrito de cebolla, pimiento rojo y ají de color en grasa o aceite.',
      'Nacarado del arroz: Mezclar el arroz con las fibras de pollo y especias.',
      'Cocción y punto: Dejar el arroz a punto meloso.',
    ],
    substitutes: 'Se puede elaborar con carne desmechada de sobras de asado o puchero.',
    pairing: 'Yuca frita o mandioca hervida y huevo de campo.',
  },
  {
    id: 'cat-bo-falso-conejo',
    name: 'Falso Conejo boliviano en salsa de arvejas',
    description: 'Bifes finos empanizados cocinados suavemente dentro de un guiso aromático de arvejas, cebolla y ají, servidos con arroz blanco.',
    difficulty: 'Fácil',
    prep_time: 30,
    instructions: '1. Pasa bifes de carne por pan rallado aplastando con fuerza y dora brevemente en sartén.\n2. En cacerola sofríe cebolla, ajo, morrón y pimentón dulce.\n3. Añade arvejas tiernas y un vaso de caldo de carne.\n4. Introduce los bifes dorados en la salsa y cocina tapado 15 minutos a fuego suave.\n5. Sirve con arroz blanco y papas cocidas.',
    servings: 3,
    recipe_ingredients: [
      { ingredient_name: 'carne' },
      { ingredient_name: 'arveja' },
      { ingredient_name: 'cebolla' },
      { ingredient_name: 'pan' },
      { ingredient_name: 'arroz' },
    ],
    origin: 'Bolivia 🇧🇴',
    chef_tips: 'El pan rallado de los bifes espesa de manera natural la salsa de arvejas, dándole un cuerpo untuoso inigualable.',
    detailed_steps: [
      'Empanado en seco: Pasar bifes magros por pan rallado seco condimentado con comino.',
      'Sellar: Dorar vuelta y vuelta en sartén con poco aceite.',
      'Ahogado de arvejas: Cocinar cebolla picada con arvejas y pimentón hasta formar salsa espesa.',
      'Cocción integrada: Sumergir la carne en la salsa para que absorba todo el sabor.',
    ],
    substitutes: 'Puedes utilizar bifes de cerdo o supremas de pollo.',
    pairing: 'Papas hervidas al dente y ensalada de lechuga y tomate.',
  },

  // ==========================================
  // --- BRASIL 🇧🇷 ---
  // ==========================================
  {
    id: 'cat-br-feijoada-casera-facil',
    name: 'Feijoada casera fácil de porotos negros',
    description: 'El plato nacional brasileño adaptado para el hogar: porotos negros cocidos con chorizo, panceta, ajo dorado y laurel, acompañados de arroz blanco y rodajas de naranja.',
    difficulty: 'Media',
    prep_time: 45,
    instructions: '1. Dora panceta y chorizo en rodajas en olla gruesa hasta desprender su aroma.\n2. Incorpora cebolla picada fina y abundante ajo picado.\n3. Agrega porotos negros cocidos o remojados con hojas de laurel y caldo.\n4. Cocina a fuego lento 30 minutos aplastando unos porotos para espesar el caldo.\n5. Sirve en cuenco hondo acompañado de arroz blanco y gajos de naranja fresca.',
    servings: 4,
    recipe_ingredients: [
      { ingredient_name: 'porotos' },
      { ingredient_name: 'chorizo' },
      { ingredient_name: 'panceta' },
      { ingredient_name: 'arroz' },
      { ingredient_name: 'cebolla' },
      { ingredient_name: 'ajo' },
    ],
    origin: 'Brasil 🇧🇷',
    chef_tips: 'La naranja fresca en gajos no es solo decorativa: su acidez cítrica corta la untuosidad de las carnes y ayuda a la digestión.',
    detailed_steps: [
      'Sofrito de ahumados: Tostar panceta y chorizo en cubos para generar grasa de cocción.',
      'Refogado brasileño: Rehogar cebolla y ajo abundante hasta perfume dorado.',
      'Hervor de feijão: Cocinar los porotos negros con caldo sustancioso y laurel.',
      'Espesado criollo: Aplastar un cucharón de porotos contra la pared de la olla y reintegrar.',
      'Acompañamiento: Emplatar con arroz blanco bien suelto y naranja pelada al vivo.',
    ],
    substitutes: 'Si no tienes porotos negros, utiliza porotos colorados o alubias con la misma técnica.',
    pairing: 'Arroz blanco al ajo, farofa crocante o pan casero y rodajas de naranja.',
  },
  {
    id: 'cat-br-escondidinho-carne',
    name: 'Escondidinho brasileño de carne con puré gratinado',
    description: 'Plato estrella de los bodegones de Brasil: jugoso guisado de carne picada sazonada oculto bajo una capa suave de puré de papas y queso gratinado.',
    difficulty: 'Fácil',
    prep_time: 35,
    instructions: '1. Saltea carne picada con cebolla, morrón, tomate en cubos, ajo y sal.\n2. Prepara un puré de papas sedoso con manteca y leche tibia.\n3. En fuente para horno vierte la carne con todo su jugo en la base.\n4. Tapa con el puré de papas alisando con espátula.\n5. Cubre con queso cremoso o rallado y gratina 15 minutos en horno caliente hasta dorar burbujeante.',
    servings: 4,
    recipe_ingredients: [
      { ingredient_name: 'carne' },
      { ingredient_name: 'papa' },
      { ingredient_name: 'queso' },
      { ingredient_name: 'cebolla' },
      { ingredient_name: 'tomate' },
      { ingredient_name: 'leche' },
    ],
    origin: 'Brasil 🇧🇷',
    chef_tips: 'Asegurarse de que la carne quede con jugo antes de cubrir con el puré para que no quede seca al gratinar.',
    detailed_steps: [
      'Guiso de relleno: Saltear cebolla y morrón con la carne picada y condimentos hasta reducir.',
      'Puré sedoso: Pisar papas calientes con manteca, leche y una pizca de pimienta.',
      'Montaje oculto: Colocar la carne en el fondo de una asadera de cerámica o vidrio térmico.',
      'Sellado cremoso: Extender el puré por encima sellando los bordes con queso.',
      'Gratinado: Llevar a horno a 220°C hasta formar costra dorada.',
    ],
    substitutes: 'Tradicionalmente se hace también con puré de mandioca (yuca) o pollo desmechado.',
    pairing: 'Ensalada verde fresca y arroz blanco.',
  },
  {
    id: 'cat-br-moqueca-pollo',
    name: 'Moqueca rápida de pollo con morrones y tomate',
    description: 'Guiso bahiano adaptado para ingredientes de casa: tiras de pollo cocinadas en capas con morrón, tomate, cebolla, ajo y crema suave o leche.',
    difficulty: 'Fácil',
    prep_time: 25,
    instructions: '1. Sazona pechuga de pollo en tiras con limón, sal y ajo.\n2. En olla o sartén honda dispón capas de cebolla en aros, morrón rojo y verde, pollo y rodajas de tomate.\n3. Riega con unas gotas de aceite y un toque de crema de leche o leche tibia.\n4. Tapa y cocina a fuego medio-bajo 18 minutos sin revolver para que las capas mantengan su forma.\n5. Sirve con cilantro o perejil fresco sobre arroz blanco.',
    servings: 2,
    recipe_ingredients: [
      { ingredient_name: 'pollo' },
      { ingredient_name: 'morron' },
      { ingredient_name: 'tomate' },
      { ingredient_name: 'cebolla' },
      { ingredient_name: 'leche' },
    ],
    origin: 'Brasil 🇧🇷',
    chef_tips: 'La clave de la moqueca es cocinar con la olla tapada sin mezclar con cuchara, permitiendo que las verduras se cocinen en sus propios jugos creando una salsa aromática natural.',
    detailed_steps: [
      'Marinado cítrico: Rociar el pollo con limón fresco y ajo machacado 10 minutos.',
      'Construcción en capas: Colocar cebolla en el fondo, pollo al centro, morrón y tomate arriba.',
      'Cocción lenta: Dejar que el vapor y los líquidos naturales formen la salsa.',
      'Toque final: Añadir un chorrito de crema o leche para enriquecer la textura.',
    ],
    substitutes: 'Puedes sustituir el pollo por filetes de merluza, pescado blanco o camarones.',
    pairing: 'Arroz blanco al vapor bien caliente.',
  },
  {
    id: 'cat-br-galinhada-mineira',
    name: 'Galinhada mineira tradicional con arroz',
    description: 'Plato clásico del estado de Minas Gerais: arroz caldoso cocinado junto a presas de pollo bien doradas, morrón, cebolla y pimentón dorado.',
    difficulty: 'Fácil',
    prep_time: 35,
    instructions: '1. Marina trozos de pollo con ajo, sal y limón.\n2. Dora el pollo en cacerola con aceite a fuego fuerte hasta que quede bien tostado por fuera.\n3. Retira parte de la grasa y rehoga en la misma olla cebolla, morrón y pimentón.\n4. Incorpora el arroz, mezcla con los jugos de cocción y vuelve a sumar el pollo.\n5. Agrega agua caliente y cocina a fuego suave 18 minutos hasta que el arroz esté en su punto.',
    servings: 3,
    recipe_ingredients: [
      { ingredient_name: 'pollo' },
      { ingredient_name: 'arroz' },
      { ingredient_name: 'cebolla' },
      { ingredient_name: 'morron' },
      { ingredient_name: 'ajo' },
    ],
    origin: 'Brasil 🇧🇷',
    chef_tips: 'Dorar muy bien el pollo al principio deja residuos caramelizados en el fondo de la olla (el "fundinho") que le da al arroz un sabor profundo y color dorado.',
    detailed_steps: [
      'Dorado intenso: Sellar las presas de pollo con piel hasta lograr una costra dorada crujiente.',
      'Desglasado: Sofreír la cebolla y el pimiento recogiendo el fondo de la olla.',
      'Cocción en una sola olla: Agregar el arroz y agua caliente, tapar y cocinar despacio.',
    ],
    substitutes: 'Puedes sumar arvejas o granos de choclo fresco al arroz durante la cocción.',
    pairing: 'Gajos de tomate fresco y ensalada de repollo.',
  },
  {
    id: 'cat-br-pao-de-queijo',
    name: 'Pão de Queijo brasileño casero al horno',
    description: 'Pancitos esponjosos y elásticos con corazón de queso fundido, elaborados con almidón de mandioca, queso rallado, leche y huevos.',
    difficulty: 'Fácil',
    prep_time: 25,
    instructions: '1. Calienta en un cazo leche con aceite y sal hasta que rompa el hervor.\n2. Vierte sobre el almidón de mandioca en un bol y mezcla con cuchara para escaldar la masa.\n3. Cuando entibie, incorpora el huevo y amasa con las manos.\n4. Añade queso rallado abundante y forma bolitas del tamaño de una nuez.\n5. Hornea a 200°C durante 18 minutos hasta que se inflen y doren ligeramente.',
    servings: 4,
    recipe_ingredients: [
      { ingredient_name: 'almidon de mandioca' },
      { ingredient_name: 'queso' },
      { ingredient_name: 'huevo' },
      { ingredient_name: 'leche' },
    ],
    origin: 'Brasil 🇧🇷',
    chef_tips: 'Escaldar el almidón con los líquidos hirviendo es el secreto para activar la elasticidad característica del pão de queijo.',
    detailed_steps: [
      'Escaldado: Verter leche y aceite hirviendo sobre el almidón para gelatinizar.',
      'Enfriado: Esperar que baje la temperatura antes de incorporar el huevo.',
      'Añadido de queso: Integrar queso cuartirolo, sardo o gouda rallado.',
      'Horno fuerte: Hornear a 200°C sin abrir la puerta para que inflen parejos.',
    ],
    substitutes: 'Si no consigues almidón de mandioca, usa fécula de maíz con una pizca de polvo para hornear.',
    pairing: 'Café negro recién colado o infusión.',
  },

  // ==========================================
  // --- PERÚ 🇵🇪 ---
  // ==========================================
  {
    id: 'cat-pe-aji-de-gallina',
    name: 'Ají de gallina tradicional peruano',
    description: 'La gran crema de la cocina criolla de Lima: pechuga de pollo deshilachada en crema sedosa de leche, pan remojado, queso y pimentón, servida sobre papas cocidas y arroz.',
    difficulty: 'Media',
    prep_time: 35,
    instructions: '1. Hierve pechuga de pollo en caldo con sal y deshiláchala en hebras finas.\n2. Remoja pan blanco en leche y licúalo con queso cremoso y pimentón o ají.\n3. En olla sofríe cebolla picada fina con ajo hasta dorar.\n4. Vierte la crema licuada a la olla y remueve a fuego bajo hasta que espese aterciopelada.\n5. Incorpora el pollo deshilachado y cocina 3 minutos. Sirve sobre papas hervidas en rodajas con arroz blanco y huevo duro.',
    servings: 4,
    recipe_ingredients: [
      { ingredient_name: 'pollo' },
      { ingredient_name: 'leche' },
      { ingredient_name: 'queso' },
      { ingredient_name: 'pan' },
      { ingredient_name: 'papa' },
      { ingredient_name: 'arroz' },
      { ingredient_name: 'huevo' },
    ],
    origin: 'Perú 🇵🇪',
    chef_tips: 'Deshilachar el pollo a mano en hebras finas (no cortarlo con cuchillo) permite que la salsa crema penetre en cada fibra de carne.',
    detailed_steps: [
      'Hervor de pollo: Cocinar la pechuga en caldo aromático 15 minutos; desmechar.',
      'Salsa base: Remojar miga de pan en leche evaporada o entera y procesar con queso fresco o parmesano.',
      'Sofrito dorado: Sofreír cebolla picada con ajo y cúrcuma/pimentón para dar el clásico color amarillo.',
      'Espesado: Cocinar la salsa hasta que tome textura de crema untuosa.',
      'Emplatado: Servir sobre cama de papas hervidas en rodajas con arroz blanco y huevo duro picado.',
    ],
    substitutes: 'El pan puede sustituirse por galletitas de agua o crackers trituradas.',
    pairing: 'Aceitunas negras, arroz blanco con choclo y copa de vino blanco fresco.',
  },
  {
    id: 'cat-pe-lomo-saltado',
    name: 'Lomo saltado peruano criollo al wok',
    description: 'Emblema del mestizaje chino-peruano: dados tiernos de lomo sellados a fuego vivo con cebolla morada, gajos gruesos de tomate, salsa de soja y papas fritas.',
    difficulty: 'Media',
    prep_time: 18,
    instructions: '1. Corta lomo o bife en tiras gruesas y salpimienta.\n2. Calienta el wok o sartén al máximo con unas gotas de aceite; sella la carne 2 minutos hasta dorar con costra.\n3. Añade cebolla en gajos gruesos y saltea 1 minuto sin que pierda firmeza.\n4. Incorpora tomate en gajos y desglasa con un chorro generoso de salsa de soja y vinagre.\n5. Agrega papas fritas crocantes al final o sírvelas al lado con arroz blanco.',
    servings: 2,
    recipe_ingredients: [
      { ingredient_name: 'carne' },
      { ingredient_name: 'cebolla' },
      { ingredient_name: 'tomate' },
      { ingredient_name: 'papa' },
      { ingredient_name: 'arroz' },
      { ingredient_name: 'soja' },
    ],
    origin: 'Perú 🇵🇪',
    chef_tips: 'Fuego al máximo y cocinar en tandas pequeñas: la carne debe dorarse rápido sin hervir para lograr el sabor ahumado característico del wok.',
    detailed_steps: [
      'Corte grueso: Cortar la cebolla y el tomate en gajos de 1.5 cm para que no se desarmen.',
      'Calor extremo: La sartén debe humear antes de tirar la carne.',
      'Salteado rápido: Mover la sartén constantemente durante 2 minutos.',
      'Salseado: El vinagre y la salsa de soja crean una emulsión instantánea con los jugos de la carne.',
      'Acompañamiento: Emplatar de inmediato con arroz blanco graneado.',
    ],
    substitutes: 'Se puede preparar con cuadril, lomo de cerdo o pechuga de pollo.',
    pairing: 'Papas fritas recién hechas y arroz blanco con choclo.',
  },
  {
    id: 'cat-pe-causa-limena',
    name: 'Causa limeña rellena de pollo y palta',
    description: 'Entrada fría clásica de Lima: suave puré de papas prensadas sazonado con limón fresco y aceite, relleno de pollo desmenuzado y láminas de palta cremosa.',
    difficulty: 'Fácil',
    prep_time: 25,
    instructions: '1. Hierve papas peladas y prénsalas en caliente hasta lograr puré liso sin grumos.\n2. Deja enfriar el puré y condiméntalo con jugo de limón fresco, aceite y sal.\n3. Mezcla pollo cocido desmenuzado con un toque suave de mayonesa o queso crema.\n4. En un molde o aro monta una capa de puré de papa, una capa de palta en láminas y el pollo.\n5. Cubre con otra capa de papa y decora con huevo duro.',
    servings: 3,
    recipe_ingredients: [
      { ingredient_name: 'papa' },
      { ingredient_name: 'pollo' },
      { ingredient_name: 'palta' },
      { ingredient_name: 'limon' },
      { ingredient_name: 'huevo' },
    ],
    origin: 'Perú 🇵🇪',
    chef_tips: 'Pisar las papas mientras están bien calientes para que no queden grumos; luego sazonar con limón una vez frías para conservar el frescor cítrico.',
    detailed_steps: [
      'Prensado: Pasar las papas dos veces por prensapapas para máxima sedosidad.',
      'Saborizado: Amasar suavemente con jugo de limón y aceite hasta que no se pegue a las manos.',
      'Armado en capas: Disponer una base de papa, colocar palta en abanico y el relleno de pollo.',
      'Terminación: Coronar con rodajas de huevo duro y aceituna.',
    ],
    substitutes: 'El pollo se puede sustituir por atún en lata escurrido con el mismo éxito.',
    pairing: 'Servir fría acompañada de hojas de lechuga fresca.',
  },
  {
    id: 'cat-pe-arroz-chaufa',
    name: 'Arroz chaufa peruano de pollo al wok',
    description: 'El clásico arroz frito chifa: arroz cocido salteado a fuego ardiente con trozos de pollo dorado, huevo revuelto tierno, cebolla de verdeo y salsa de soja.',
    difficulty: 'Fácil',
    prep_time: 15,
    instructions: '1. En sartén caliente haz un revuelto rápido con los huevos y resérvalos picados.\n2. En la misma sartén dora dados de pollo con jengibre rallado o ajo a fuego fuerte.\n3. Añade arroz blanco cocido frío del día anterior y saltea vigorosamente desgranándolo.\n4. Vierte salsa de soja sobre el arroz y saltea hasta que tome color parejo tostado.\n5. Incorpora el huevo revuelto y abundante cebolla de verdeo picada justo antes de apagar el fuego.',
    servings: 2,
    recipe_ingredients: [
      { ingredient_name: 'arroz' },
      { ingredient_name: 'pollo' },
      { ingredient_name: 'huevo' },
      { ingredient_name: 'cebolla' },
      { ingredient_name: 'soja' },
    ],
    origin: 'Perú 🇵🇪',
    chef_tips: 'Utilizar arroz cocido del día anterior bien frío de la nevera: los granos secos y firmes se saltean sin apelmazarse ni pegarse.',
    detailed_steps: [
      'Tortilla base: Hacer huevos revueltos jugosos y trocear.',
      'Dorado del ave: Saltear pechuga en cubos pequeños con una gota de aceite.',
      'Fritura del arroz: Echar el arroz frío desgranándolo con espátula.',
      'Aromas finales: Salpicar con salsa de soja y verdeo fresco en el último segundo.',
    ],
    substitutes: 'Puedes sumar trocitos de carne vacuna, jamón cocido o salchicha.',
    pairing: 'Sopa wantán o té de jazmín caliente.',
  },
  {
    id: 'cat-pe-seco-de-carne',
    name: 'Seco de carne limeño con papas y arvejas',
    description: 'Guiso noble de carne de res estofada en salsa verde aromática de cilantro, cebolla, ajo, zanahoria y arvejas tiernas con arroz blanco.',
    difficulty: 'Media',
    prep_time: 40,
    instructions: '1. Corta carne vacuna en dados medianos y dora en olla con aceite caliente.\n2. Licua un atado de cilantro fresco con un poco de agua o caldo hasta lograr un puré verde intenso.\n3. Rehoga cebolla y ajo en la olla, incorpora la salsa verde de cilantro y regresa la carne.\n4. Suma zanahoria en rodajas, papas en cubos y caldo; cocina 25 minutos tapado hasta que la carne esté tierna.\n5. Agrega arvejas los últimos 5 minutos y sirve con arroz blanco.',
    servings: 3,
    recipe_ingredients: [
      { ingredient_name: 'carne' },
      { ingredient_name: 'papa' },
      { ingredient_name: 'arveja' },
      { ingredient_name: 'zanahoria' },
      { ingredient_name: 'cebolla' },
      { ingredient_name: 'arroz' },
    ],
    origin: 'Perú 🇵🇪',
    chef_tips: 'Licuar el cilantro crudo y añadirlo inmediatamente al sofrito para que conserve su color verde vivo y perfume cítrico.',
    detailed_steps: [
      'Sellado de la carne: Dorar trozos de palomita, osobuco o cuadril.',
      'Concentrado verde: Procesar hojas frescas de cilantro.',
      'Estofado lento: Cocinar a fuego bajo tapado para que la carne absorba la salsa.',
      'Verduras: Agregar papas y zanahorias que espesarán la salsa al cocinarse.',
    ],
    substitutes: 'Rinde igualmente delicioso con carne de cerdo o presas de pollo.',
    pairing: 'Arroz blanco con ajo y frijoles o porotos cocidos.',
  },

  // ==========================================
  // --- COLECCIÓN COMPLETA DE FAROFAS BRASILEÑAS 🇧🇷 ---
  // ==========================================
  {
    id: 'cat-br-farofa-tradicional-manteiga',
    name: 'Farofa tradicional brasileña con manteca y cebolla dorada',
    description: 'La guarnición reina de Brasil: harina de mandioca (o harina de maíz fina) tostada lentamente en generosa manteca con cebolla caramelizada y ajo crujiente.',
    difficulty: 'Fácil',
    prep_time: 15,
    instructions: '1. Derrite abundante manteca en sartén amplia a fuego medio.\n2. Agrega cebolla picada fina y rehoga hasta que tome color dorado acaramelado.\n3. Incorpora ajo picado y cocina 1 minuto sin quemar.\n4. Vierte la harina de mandioca (o harina de maíz) poco a poco, mezclando continuamente con cuchara de madera.\n5. Tuesta a fuego medio-bajo durante 6 a 8 minutos hasta que la harina quede seca, dorada y bien crocante. Sazona con sal y pimienta.',
    servings: 4,
    recipe_ingredients: [
      { ingredient_name: 'mandioca' },
      { ingredient_name: 'manteca' },
      { ingredient_name: 'cebolla' },
      { ingredient_name: 'ajo' },
    ],
    origin: 'Brasil 🇧🇷',
    chef_tips: 'El secreto de una gran farofa es tostar a fuego suave sin dejar de remover con cuchara de madera: debe sentirse crocante al morder ("crocantinha") pero humedecida por la manteca.',
    detailed_steps: [
      'Grasa noble: Usar manteca pura en lugar de solo aceite para aportar aroma tostado.',
      'Punto de cebolla: Dejar dorar bien la cebolla para que endulce naturalmente.',
      'Tostado continuo: Añadir la harina en lluvia e integrar removiendo el fondo para no quemar.',
      'Terminación: Retirar del fuego y espolvorear perejil fresco o cebollita de verdeo.',
    ],
    substitutes: 'Si no consigues harina de mandioca tostada, usa harina de maíz precocida, polenta fina tostada o pan rallado grueso.',
    pairing: 'Compañera inseparable de feijoada, carnes asadas, pollo al horno o arroz con porotos.',
  },
  {
    id: 'cat-br-farofa-de-ovo',
    name: 'Farofa de huevo rápida y húmeda (Farofa de ovo)',
    description: 'El clásico hogareño más popular de Brasil: huevos revueltos jugosos envueltos en harina de mandioca tostada con manteca y verdeo fresco.',
    difficulty: 'Fácil',
    prep_time: 12,
    instructions: '1. En sartén derrite manteca y sofríe cebolla picada con una pizca de sal.\n2. Abre espacio en el centro y casca los huevos enteros.\n3. Revuelve los huevos suavemente para dejarlos en trozos tiernos y jugosos (no sobrecocinar).\n4. Agrega la harina de mandioca o maíz sobre los huevos aún húmedos.\n5. Mezcla rápidamente 2 minutos para que la harina absorba la manteca y el huevo. Espolvorea cebolla de verdeo y sirve tibia.',
    servings: 2,
    recipe_ingredients: [
      { ingredient_name: 'huevo' },
      { ingredient_name: 'mandioca' },
      { ingredient_name: 'manteca' },
      { ingredient_name: 'cebolla' },
    ],
    origin: 'Brasil 🇧🇷',
    chef_tips: 'No seques los huevos antes de tirar la harina: la harina debe hidratarse con la humedad del huevo tierno para lograr la textura húmeda característica ("farofa molhadinha").',
    detailed_steps: [
      'Sofrito: Saltear cebolla en manteca hasta transparente.',
      'Cocción del huevo: Cascar los huevos directamente en la sartén y romper yemas sin batir en exceso.',
      'Incorporación: Echar la harina cuando el huevo esté a medio cuajar.',
      'Final: Ajustar sal y agregar verdeo o perejil fresco picado.',
    ],
    substitutes: 'Puedes enriquecerla con dados de queso fresco o jamón.',
    pairing: 'Bifes a la plancha, arroz blanco caliente o milanesas.',
  },
  {
    id: 'cat-br-farofa-bacon-crocante',
    name: 'Farofa crocante con panceta ahumada y ajo dorado',
    description: 'Farofa festiva de sabor intenso: panceta cortada en cubitos bien dorada en su propia grasa con abundante ajo y harina de mandioca crujiente.',
    difficulty: 'Fácil',
    prep_time: 15,
    instructions: '1. En sartén dora panceta en cubitos a fuego medio hasta que desprenda su grasa y quede bien crujiente.\n2. Agrega cebolla picada y ajo laminado en la misma grasa del bacon.\n3. Cuando doren, añade una cucharada de manteca para redondear el sabor.\n4. Suma la harina de mandioca y tuesta a fuego bajo durante 5 minutos mezclando parejo.\n5. Retira del fuego, sazona al gusto y sirve crujiente.',
    servings: 4,
    recipe_ingredients: [
      { ingredient_name: 'panceta' },
      { ingredient_name: 'mandioca' },
      { ingredient_name: 'cebolla' },
      { ingredient_name: 'ajo' },
      { ingredient_name: 'manteca' },
    ],
    origin: 'Brasil 🇧🇷',
    chef_tips: 'Aprovecha al 100% la grasa que suelta la panceta para tostar la harina; le otorga un sabor ahumado profundo imposible de igualar.',
    detailed_steps: [
      'Extracción de grasa: Cocinar la panceta a fuego medio sin agregar aceite.',
      'Aromas: Tostar el ajo y la cebolla en la grasa viva.',
      'Tostado parejo: Volcar la harina de mandioca y tostar sin descuidar el fondo.',
      'Toque verde: Finalizar con perejil o ciboulette picado.',
    ],
    substitutes: 'Se puede preparar con chorizo criollo desgranado o jamón crudo en cubos.',
    pairing: 'Asado, costillitas de cerdo, churrasco o feijoada.',
  },
  {
    id: 'cat-br-farofa-banana',
    name: 'Farofa agridulce de banana dorada en manteca',
    description: 'Maravillosa especialidad brasileña: rodajas de banana caramelizadas en manteca fundida combinadas con el crocante de la harina de mandioca tostada.',
    difficulty: 'Fácil',
    prep_time: 15,
    instructions: '1. Corta bananas firmes en rodajas o medias lunas medianas.\n2. En sartén derrite manteca a fuego medio y dora la cebolla picada fina.\n3. Incorpora las rodajas de banana y dóralas con cuidado 2 minutos por lado sin desarmarlas.\n4. Añade la harina de mandioca o harina de maíz tostándola suavemente alrededor de las bananas.\n5. Mezcla con delicadeza para no hacer puré las bananas. Sazona con un toque de sal marina para contrastar.',
    servings: 3,
    recipe_ingredients: [
      { ingredient_name: 'banana' },
      { ingredient_name: 'mandioca' },
      { ingredient_name: 'manteca' },
      { ingredient_name: 'cebolla' },
    ],
    origin: 'Brasil 🇧🇷',
    chef_tips: 'Usar bananas en su punto justo (amarillas pero firmes, no pasadas ni maduras en exceso) para que mantengan su bocado al saltearse en la manteca.',
    detailed_steps: [
      'Corte parejo: Rodajas de banana de 1 cm de grosor.',
      'Caramelizado: Dorar en manteca hasta tomar color ámbar sutil.',
      'Tostado delicado: Incorporar la harina envolviendo con espátula.',
      'Equilibrio: El contraste entre la sal de la manteca y el azúcar natural de la fruta es mágico.',
    ],
    substitutes: 'Si no tienes banana, puedes usar manzana verde en cubitos o pasas de uva.',
    pairing: 'Pescados fritos, carnes asadas o lomo de cerdo al horno.',
  },
  {
    id: 'cat-br-farofa-cenoura',
    name: 'Farofa húmeda de zanahoria rallada y verdeo',
    description: 'Farofa colorida, húmeda y nutritiva: abundante zanahoria rallada cocinada en manteca hasta fundirse y teñir la harina de un tono dorado brillante.',
    difficulty: 'Fácil',
    prep_time: 15,
    instructions: '1. Ralla zanahoria por la parte fina o mediana del rallador.\n2. En sartén sofríe cebolla picada y ajo en manteca derretida.\n3. Añade la zanahoria rallada y rehoga 3 minutos hasta que suelte su color naranja y se ablande.\n4. Incorpora la harina de mandioca mezclando para teñirla de forma homogénea.\n5. Tuesta 4 minutos a fuego suave, ajusta sal y corona con verdeo picado.',
    servings: 4,
    recipe_ingredients: [
      { ingredient_name: 'zanahoria' },
      { ingredient_name: 'mandioca' },
      { ingredient_name: 'manteca' },
      { ingredient_name: 'cebolla' },
      { ingredient_name: 'ajo' },
    ],
    origin: 'Brasil 🇧🇷',
    chef_tips: 'La zanahoria aporta jugo dulce y natural, logrando una farofa que no resulta seca al paladar y que encanta a grandes y chicos.',
    detailed_steps: [
      'Rallado fino: La zanahoria debe integrarse con la textura de la harina.',
      'Cocción: Rehogar en manteca para extraer el betacaroteno que colorea el plato.',
      'Tostado: Unir con la harina hasta que quede suelta pero jugosa.',
    ],
    substitutes: 'Puedes agregar zuchini o zapallito rallado escurrido.',
    pairing: 'Pollo al horno con hierbas, milanesas o pescado a la plancha.',
  },
  {
    id: 'cat-br-farofa-rica-linguiça',
    name: 'Farofa rica con chorizo desgranado y choclo tierno',
    description: 'Farofa completa y sustanciosa: chorizo desmenuzado y dorado con granos de choclo dulce, cebolla, pimentón y harina de mandioca crocante.',
    difficulty: 'Fácil',
    prep_time: 20,
    instructions: '1. Retira la piel al chorizo y desmenuza la carne en una sartén caliente.\n2. Saltea hasta que esté bien dorada y crocante.\n3. Suma cebolla picada y granos de choclo dulce; cocina 3 minutos.\n4. Añade una cucharada de manteca y la harina de mandioca.\n5. Tuesta todo junto 5 minutos a fuego medio revolviendo hasta lograr un tostado parejo.',
    servings: 4,
    recipe_ingredients: [
      { ingredient_name: 'chorizo' },
      { ingredient_name: 'choclo' },
      { ingredient_name: 'mandioca' },
      { ingredient_name: 'cebolla' },
      { ingredient_name: 'manteca' },
    ],
    origin: 'Brasil 🇧🇷',
    chef_tips: 'El contraste de texturas entre el grano tierno y dulce del choclo y el chorizo crocante con la harina tostada la convierte en un plato que puede comerse casi solo.',
    detailed_steps: [
      'Dorado del relleno: Dorar el chorizo sin piel hasta deshacerlo en pedacitos.',
      'Suma de choclo: Incorporar granos frescos o en conserva bien escurridos.',
      'Tostado integral: Integrar la harina y tostar con paciencia.',
    ],
    substitutes: 'Queda excelente con salchicha parrillera o panceta.',
    pairing: 'Churrasco, arroz blanco y ensalada de tomate.',
  },

  // ==========================================
  // --- CLÁSICOS BRASILEÑOS ADICIONALES 🇧🇷 ---
  // ==========================================
  {
    id: 'cat-br-strogonoff-frango',
    name: 'Strogonoff brasileño de pollo con crema y papas pay',
    description: 'El plato casero preferido de todo Brasil: dados de pollo salteados con cebolla, salsa de tomate, mostaza y crema de leche suave, servido con arroz blanco y lluvia de papas pay crocantes.',
    difficulty: 'Fácil',
    prep_time: 25,
    instructions: '1. Corta pechuga de pollo en cubos chicos y dóralos a fuego fuerte en sartén con manteca y aceite.\n2. Agrega cebolla picada fina y ajo; cocina hasta dorar.\n3. Añade salsa de tomate (o ketchup) y una cucharadita de mostaza; mezcla bien.\n4. Baja el fuego al mínimo e incorpora crema de leche; calienta 2 minutos sin dejar que hierva para que no se corte.\n5. Sirve en plato con arroz blanco de un lado y corona con abundante lluvia de papas pay crocantes.',
    servings: 3,
    recipe_ingredients: [
      { ingredient_name: 'pollo' },
      { ingredient_name: 'crema' },
      { ingredient_name: 'tomate' },
      { ingredient_name: 'papa' },
      { ingredient_name: 'arroz' },
      { ingredient_name: 'cebolla' },
    ],
    origin: 'Brasil 🇧🇷',
    chef_tips: 'Añadir la crema de leche siempre a fuego muy bajo y apagar antes de que rompa en hervor para conservar una salsa sedosa y brillante.',
    detailed_steps: [
      'Sellado rápido: Saltear el pollo a fuego vivo para que quede tierno y jugoso.',
      'Base de sabor: Combinar tomate con mostaza para el toque agridulce característico.',
      'Crema suave: Incorporar crema fresca o nata espesa.',
      'Emplatado canónico: Mitad arroz blanco suelto, mitad strogonoff cremoso y papas pay crocantes por encima.',
    ],
    substitutes: 'Se pueden sumar champiñones laminados o choclo en grano.',
    pairing: 'Arroz blanco bien caliente y ensalada de hojas verdes.',
  },
  {
    id: 'cat-br-strogonoff-carne',
    name: 'Strogonoff paulista de carne tierna con crema suave',
    description: 'Versión clásica de carne vacuna en tiras finas selladas, estofadas en salsa de mostaza, tomate dulce y crema de leche untuosa con papas doradas.',
    difficulty: 'Fácil',
    prep_time: 25,
    instructions: '1. Corta carne vacuna (lomo, cuadril o nalga) en tiras delgadas.\n2. Sella la carne a fuego muy fuerte en tandas para conservar sus jugos.\n3. En la misma sartén rehoga cebolla picada con ajo.\n4. Incorpora salsa de tomate y mostaza; reintegra la carne con sus jugos.\n5. Agrega crema de leche, remueve a fuego mínimo 2 minutos y sirve con arroz y papas.',
    servings: 3,
    recipe_ingredients: [
      { ingredient_name: 'carne' },
      { ingredient_name: 'crema' },
      { ingredient_name: 'tomate' },
      { ingredient_name: 'arroz' },
      { ingredient_name: 'cebolla' },
      { ingredient_name: 'papa' },
    ],
    origin: 'Brasil 🇧🇷',
    chef_tips: 'Sellar la carne en tandas rápidas sin amontonar en la sartén para evitar que hierva; debe dorarse en segundos.',
    detailed_steps: [
      'Corte de carne: Tiras tipo bocado transversales a la fibra.',
      'Desglasado: Levantar el fondo caramelizado de la sartén con la salsa de tomate.',
      'Salsa cremosa: Integrar la crema de leche fuera del hervor violento.',
    ],
    substitutes: 'Rinde igual de exquisito con carne de cerdo magra.',
    pairing: 'Papas fritas o papas pay y vino tinto joven.',
  },
  {
    id: 'cat-br-brigadeiro-caseiro',
    name: 'Brigadeiros artesanales de chocolate y manteca',
    description: 'El bocado dulce más emblemático de Brasil: trufas cremosas de leche condensada cocinada con cacao y manteca, moldeadas a mano y rebozadas en chocolate.',
    difficulty: 'Fácil',
    prep_time: 20,
    instructions: '1. En cacerola pequeña mezcla leche condensada, cacao en polvo (o chocolate) y manteca.\n2. Cocina a fuego medio-bajo revolviendo continuamente con espátula de silicona.\n3. Cuando la masa espese y se despegue completamente del fondo de la cacerola (punto brigadeiro), retira del fuego.\n4. Vierte en plato enmantecado y deja enfriar por completo.\n5. Úntate las manos con un toque de manteca, forma bolitas y pásalas por granas de chocolate o cacao amargo.',
    servings: 4,
    recipe_ingredients: [
      { ingredient_name: 'leche' },
      { ingredient_name: 'chocolate' },
      { ingredient_name: 'manteca' },
    ],
    origin: 'Brasil 🇧🇷',
    chef_tips: 'El "punto brigadeiro" se reconoce cuando al pasar la espátula por el medio del fondo de la olla, la mezcla tarda varios segundos en volver a unirse.',
    detailed_steps: [
      'Fuego controlado: Cocinar a fuego suave para que el azúcar de la leche no se queme.',
      'Enfriado total: Dejar enfriar antes de moldear para que tome cuerpo firme.',
      'Boleado: Usar apenas una gota de manteca en las palmas de las manos.',
    ],
    substitutes: 'Se puede rebozar en coco rallado para hacer "Beijinho" de coco.',
    pairing: 'Café solo o infusión caliente.',
  },

  // ==========================================
  // --- CLÁSICOS CRIOLLOS Y REGIONALES INFALTABLES 🇦🇷 🇺🇾 🇵🇾 ---
  // ==========================================
  {
    id: 'cat-ar-polenta-tuco',
    name: 'Polenta cremosa con tuco criollo de carne y queso derretido',
    description: 'Confort de hogar indispensable: polenta de maíz cocida en leche y manteca, cubierta con generoso tuco estofado de carne, tomate y abundante queso mantecoso.',
    difficulty: 'Fácil',
    prep_time: 30,
    instructions: '1. En olla prepara el tuco: dora carne picada o trozos de carne con cebolla, morrón y puré de tomate; condimenta con laurel y orégano 20 min.\n2. En otra olla hierve leche con agua, sal y una cucharada de manteca.\n3. Vierte la harina de maíz en forma de lluvia fina revolviendo con batidor de alambre para evitar grumos.\n4. Cocina 2 a 3 minutos hasta que espese y esté cremosa.\n5. Sirve la polenta caliente en fuente, hunde cubos de queso cremoso en el centro y cubre con el tuco caliente de carne y queso rallado.',
    servings: 4,
    recipe_ingredients: [
      { ingredient_name: 'polenta' },
      { ingredient_name: 'carne' },
      { ingredient_name: 'tomate' },
      { ingredient_name: 'queso' },
      { ingredient_name: 'leche' },
      { ingredient_name: 'cebolla' },
      { ingredient_name: 'manteca' },
    ],
    origin: 'Argentina 🇦🇷',
    chef_tips: 'Cocinar la polenta combinando leche y manteca le otorga una sedosidad similar a la de un restaurante de pasta artesanal italiana.',
    detailed_steps: [
      'Estofado previo: El tuco debe estar bien cocido y denso antes de tirar la polenta.',
      'Lluvia sin grumos: Echar la polenta despacio mientras se bate vigorosamente.',
      'Fundición de queso: Colocar el queso mantecoso debajo del tuco caliente para que se funda en hilos.',
    ],
    substitutes: 'El tuco se puede hacer con salchichas parrilleras o boloñesa vegetal con hongos.',
    pairing: 'Vino tinto Malbec o Bonarda y pan de campo.',
  },
  {
    id: 'cat-ar-polenta-frita',
    name: 'Bastones crocantes de polenta frita dorada con queso',
    description: 'Aperitivo clásico de bodegón: polenta fría cortada en bastones gruesos dorados en sartén con aceite hasta lograr una corteza ultra crocante y corazón tierno.',
    difficulty: 'Fácil',
    prep_time: 20,
    instructions: '1. Cocina polenta espesa y viértela en una asadera rectangular aceitada; deja enfriar hasta que solidifique.\n2. Corta la polenta fría en bastones del tamaño de papas fritas gruesas.\n3. Fríe en sartén con abundante aceite caliente hasta que estén dorados y crocantes por todos sus lados.\n4. Escurre sobre papel absorbente y espolvorea con queso rallado, sal fina y pimentón.\n5. Sirve calientes como snack o guarnición.',
    servings: 3,
    recipe_ingredients: [
      { ingredient_name: 'polenta' },
      { ingredient_name: 'queso' },
      { ingredient_name: 'manteca' },
    ],
    origin: 'Argentina 🇦🇷',
    chef_tips: 'La polenta debe estar completamente fría y firme de la heladera antes de cortar para que los bastones mantengan su forma perfecta en la sartén.',
    detailed_steps: [
      'Enfriado plano: Extender a 2 cm de grosor en bandeja.',
      'Fritura a fuego alto: No amontonar bastones en la sartén.',
      'Crocancia: Tostar hasta que la superficie suene seca al golpear con pinza.',
    ],
    substitutes: 'Se pueden hornear a 220°C con un chorrito de aceite de oliva.',
    pairing: 'Salsa tártara, mayonesa al ajo o salsa de tomate especiada.',
  },
  {
    id: 'cat-ar-revuelto-gramajo',
    name: 'Revuelto Gramajo porteño tradicional con papas pay y jamón',
    description: 'Icono de los bistrós de Buenos Aires: papas pay finas y doradas salteadas con jamón cocido en juliana, arvejas tiernas y huevos cuajados a punto babé.',
    difficulty: 'Fácil',
    prep_time: 20,
    instructions: '1. Corta papas en tiras finísimas (papas pay) y fríelas en aceite caliente hasta que queden rubias y crocantes; reserva.\n2. En sartén amplia con una nuez de manteca saltea jamón cocido en tiras y cebolla picada 2 minutos.\n3. Agrega arvejas escurridas y saltea 1 minuto.\n4. Incorpora las papas pay fritas a la sartén.\n5. Vierte huevos batidos con sal y pimienta; remueve con espátula a fuego medio apenas 60 segundos retirando antes de que sequen para lograr el punto babé cremoso.',
    servings: 2,
    recipe_ingredients: [
      { ingredient_name: 'papa' },
      { ingredient_name: 'huevo' },
      { ingredient_name: 'jamon' },
      { ingredient_name: 'arveja' },
      { ingredient_name: 'cebolla' },
      { ingredient_name: 'manteca' },
    ],
    origin: 'Argentina 🇦🇷',
    chef_tips: 'El revuelto Gramajo auténtico debe ser "babé" (jugoso y cremoso), nunca una tortilla seca; el calor residual termina de ligar el huevo fuera del fuego.',
    detailed_steps: [
      'Papas pay secas: Dejar escurrir bien las papas para que aporten crujido.',
      'Salteado de embutido: Calentar el jamón sin quemar.',
      'Unión relámpago: Apagar el fuego cuando el huevo aún esté húmedo y brillante.',
    ],
    substitutes: 'Si no tienes jamón, queda riquísimo con panceta crocante o pollo.',
    pairing: 'Pan blanco tostado y ensalada de tomates frescos.',
  },
  {
    id: 'cat-ar-matambre-pizza',
    name: 'Matambre a la pizza al horno con queso gratinado y tomate',
    description: 'Gran clásico del asado argentino: corte tierno de matambre tiernizado al horno, cubierto con salsa de tomate casera, queso derretido en hebras y orégano.',
    difficulty: 'Media',
    prep_time: 45,
    instructions: '1. Desgrasa el matambre y colócalo en asadera para horno con leche o caldo durante 25 minutos tapado con aluminio para tiernizar.\n2. Retira el papel, coloca el matambre con la grasa hacia abajo y dora a fuego fuerte 10 minutos.\n3. Vierte salsa de tomate espesa con ajo y orégano sobre toda la superficie de la carne.\n4. Cubre generosamente con queso cremoso o mozzarella en rodajas.\n5. Hornea a 220°C hasta que el queso se derrita formando costra dorada; decora con rodajas de tomate y orégano.',
    servings: 4,
    recipe_ingredients: [
      { ingredient_name: 'carne' },
      { ingredient_name: 'queso' },
      { ingredient_name: 'tomate' },
      { ingredient_name: 'leche' },
      { ingredient_name: 'ajo' },
    ],
    origin: 'Argentina 🇦🇷',
    chef_tips: 'Cocinar primero tapado con leche en el horno ablanda el colágeno del matambre, transformando un corte fibroso en pura mantequilla que se corta con tenedor.',
    detailed_steps: [
      'Tiernizado: Hornear con líquido tapado herméticamente.',
      'Cobertura tipo pizza: Extender salsa densa que no humedezca de más la carne.',
      'Gratinado potente: Dorar el queso a fuego superior de horno.',
    ],
    substitutes: 'Se puede preparar con colita de cuadril abierta al medio o pechugas de pollo.',
    pairing: 'Papas rústicas al romero y vino tinto.',
  },
  {
    id: 'cat-ar-humita-olla',
    name: 'Humita en olla norteña cremosa con queso mantecoso',
    description: 'Manjar ancestral del norte andino: choclo fresco rallado o procesado cocinado a fuego lento con cebolla, morrón dulce, zapallo cremoso y corazón de queso que se funde.',
    difficulty: 'Media',
    prep_time: 35,
    instructions: '1. Ralla o procesa granos de choclo fresco con un chorrito de leche hasta lograr una crema espesa.\n2. En olla rehoga cebolla y morrón picados finos en manteca o aceite con pimentón dulce y comino.\n3. Agrega puré de zapallo cocido y la crema de choclo procesada.\n4. Cocina a fuego lento durante 20 minutos revolviendo con cuchara de madera para que no se pegue al fondo.\n5. Agrega cubos de queso cremoso o cuartirolo al servir para que se fundan con el calor de la humita.',
    servings: 4,
    recipe_ingredients: [
      { ingredient_name: 'choclo' },
      { ingredient_name: 'zapallo' },
      { ingredient_name: 'queso' },
      { ingredient_name: 'cebolla' },
      { ingredient_name: 'morron' },
      { ingredient_name: 'leche' },
      { ingredient_name: 'manteca' },
    ],
    origin: 'Argentina 🇦🇷',
    chef_tips: 'El zapallo pisado no solo aporta color dorado intenso sino que equilibra el almidón del choclo dejando una textura aterciopelada insuperable.',
    detailed_steps: [
      'Sofrito norteño: Cebolla y morrón con pimentón dulce de buena calidad.',
      'Choclo procesado: Licuar la mitad de los choclos y dejar algunos granos enteros para textura.',
      'Cocción paciente: Revolver continuamente hasta que el choclo cambie de color y espese.',
    ],
    substitutes: 'Si no es temporada de choclo fresco, utiliza choclo congelado o en lata escurrido.',
    pairing: 'Salsa yasgua picante de tomate y ají, vino Torrontés norteño.',
  },
  {
    id: 'cat-ar-guiso-lentejas',
    name: 'Guiso de lentejas casero con panceta, chorizo y papas',
    description: 'El rey de los días fríos: lentejas tiernas estofadas con chorizo en rodajas, panceta ahumada, zanahoria, cebolla y papas en cubos en salsa de tomate especiada.',
    difficulty: 'Fácil',
    prep_time: 40,
    instructions: '1. En olla dora panceta en cubos y rodajas de chorizo hasta desprender aroma.\n2. Suma cebolla, morrón y zanahoria en cubitos; rehoga 5 minutos.\n3. Agrega puré de tomate, pimentón dulce, una hoja de laurel y las lentejas.\n4. Cubre con caldo caliente y cocina a fuego medio 20 minutos.\n5. Incorpora papas en dados y cocina 15 minutos más hasta que todo esté tierno y el caldo espeso.',
    servings: 4,
    recipe_ingredients: [
      { ingredient_name: 'lenteja' },
      { ingredient_name: 'chorizo' },
      { ingredient_name: 'panceta' },
      { ingredient_name: 'papa' },
      { ingredient_name: 'zanahoria' },
      { ingredient_name: 'cebolla' },
      { ingredient_name: 'tomate' },
    ],
    origin: 'Argentina 🇦🇷',
    chef_tips: 'Agregar las papas en la segunda mitad de la cocción para que queden tiernas pero enteras, y dejen soltar su almidón para espesar naturalmente el guiso.',
    detailed_steps: [
      'Dorado de embutidos: Sellar para fijar sabor ahumado.',
      'Sofrito criollo: Sudoración de cebolla y morrón.',
      'Hervor de legumbres: Cocinar a fuego calmo para que las lentejas no revienten su piel.',
    ],
    substitutes: 'Versión vegetariana omitiendo embutidos y sumando zapallo y calabaza.',
    pairing: 'Pan crujiente para mojar el caldo y vino tinto con cuerpo.',
  },
  {
    id: 'cat-pe-papa-huancaina',
    name: 'Papa a la huancaína tradicional con salsa de queso y ají',
    description: 'Entrada cumbre de la gastronomía peruana: rodajas de papas hervidas bañadas en crema sedosa de queso fresco, galletas o pan, leche y ají dorado, decoradas con huevo duro.',
    difficulty: 'Fácil',
    prep_time: 20,
    instructions: '1. Hierve papas peladas en agua con sal hasta que estén tiernas pero firmes; córtalas en rodajas gruesas.\n2. En sartén dora cebolla y ajo picados con ají amarillo (o pimentón dulce).\n3. En licuadora coloca queso fresco, leche, el sofrito de cebolla y 4 galletitas de agua o miga de pan.\n4. Licua a máxima potencia hasta lograr una crema homogénea, espesa y aterciopelada.\n5. Coloca las papas en el plato, baña generosamente con la salsa huancaína y decora con rodajas de huevo duro y aceitunas.',
    servings: 4,
    recipe_ingredients: [
      { ingredient_name: 'papa' },
      { ingredient_name: 'queso' },
      { ingredient_name: 'leche' },
      { ingredient_name: 'huevo' },
      { ingredient_name: 'cebolla' },
      { ingredient_name: 'ajo' },
    ],
    origin: 'Perú 🇵🇪',
    chef_tips: 'La textura perfecta de la huancaína debe cubrir la cuchara sin gotear; las galletitas de agua o el pan son el emulsionante clave que le otorga cuerpo y suavidad.',
    detailed_steps: [
      'Cocción de papas: Mantener al dente y dejar enfriar a temperatura ambiente.',
      'Emulsión en licuadora: Procesar el queso con leche gradualmente para no licuar de más.',
      'Servido frío o tibio: Sobre hojas de lechuga fresca.',
    ],
    substitutes: 'El queso fresco se puede sustituir por ricota con una cucharada de queso crema.',
    pairing: 'Chicha morada fresca o cerveza rubia.',
  },
  {
    id: 'cat-pe-salchipapa',
    name: 'Salchipapas criollas con papas doradas crocantes y salsas caseras',
    description: 'La comida al paso más querida de Sudamérica: papas fritas caseras bien crocantes coronadas con salchichas en rodajas doradas al sartén y salsas.',
    difficulty: 'Fácil',
    prep_time: 15,
    instructions: '1. Corta papas en bastones parejos y fríelas en aceite bien caliente hasta que queden doradas y crujientes.\n2. En sartén corta salchichas en rodajas diagonales con cortes en los extremos y dóralas a fuego fuerte hasta que se abran.\n3. Coloca una montaña de papas fritas en una fuente o cono.\n4. Distribuye las salchichas doradas calientes por encima.\n5. Sazona con sal marina y acompaña con mayonesa casera, ketchup o salsa golf.',
    servings: 2,
    recipe_ingredients: [
      { ingredient_name: 'papa' },
      { ingredient_name: 'salchicha' },
    ],
    origin: 'Perú 🇵🇪',
    chef_tips: 'Hacer cortes en cruz en las puntas de las salchichas antes de freírlas para que se abran como pulpos y queden con bordes extracrocantes.',
    detailed_steps: [
      'Doble fritura de papa: Blanquear primero y dorar a fuego fuerte para máxima crocancia.',
      'Salchichas al punto: Dorar en sartén con apenas unas gotas de aceite.',
    ],
    substitutes: 'Se puede preparar con chorizo o salchicha parrillera.',
    pairing: 'Gaseosa bien fría o limonada con menta.',
  },
]
